# Generated by Django 2.2 on 2019-06-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_person', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
