# Generated by Django 2.2 on 2019-06-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rent',
            name='image',
            field=models.ImageField(default='', upload_to='lend/images'),
        ),
        migrations.AddField(
            model_name='rent',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rent',
            name='sub_category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
